### ISSUE TITLE
Raster-version of KA shows wrong categories

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/nin-kartdataflyt#46]
Raster-export for KA must implement same values as used for mbtiles:

PointInfo
![image](https://user-images.githubusercontent.com/3570752/39995474-921b3636-577c-11e8-9804-c4a8e807964c.png)

Vector-tile
![image](https://user-images.githubusercontent.com/3570752/39995497-aa9190a2-577c-11e8-99cb-3601112aa426.png)

**Comment by bjornreppen** [comment]
Ferdig
